/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#eff0fa',
        'primary-fixed-dim': '#adc7ff',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#00722f',
        'on-surface-variant': '#414754',
        'on-secondary-fixed-variant': '#005320',
        'on-tertiary-container': '#0a0400',
        'google-yellow': '#f9ab00',
        'google-blue': '#1a73e8',
        surface: '#f9f9ff',
        'surface-variant': '#e0e2ec',
        'google-green': '#34a853',
        'secondary-container': '#86f898',
        secondary: '#006e2c',
        'surface-container-highest': '#e0e2ec',
        'error-container': '#ffdad6',
        'inverse-primary': '#adc7ff',
        'inverse-surface': '#2d3038',
        'on-primary-fixed-variant': '#004493',
        'primary-container': '#1a73e8',
        'surface-bright': '#f9f9ff',
        primary: '#005bbf',
        error: '#ba1a1a',
        outline: '#727785',
        'surface-tint': '#005bc0',
        'outline-variant': '#c1c6d6',
        'secondary-fixed': '#89fa9b',
        'on-secondary': '#ffffff',
        'surface-container': '#ecedf7',
        'on-secondary-fixed': '#002108',
        'tertiary-fixed': '#ffddb0',
        'on-tertiary-fixed-variant': '#614000',
        'on-background': '#191c23',
        'primary-fixed': '#d8e2ff',
        tertiary: '#805600',
        'on-primary-fixed': '#001a41',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#e6e8f2',
        'google-red': '#d93025',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#281800',
        'tertiary-fixed-dim': '#ffba45',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#6ddd81',
        'tertiary-container': '#a06d00',
        'surface-dim': '#d8d9e3',
        'surface-container-low': '#f2f3fd',
        'on-surface': '#191c23',
        'on-primary-container': '#ffffff',
        background: '#f9f9ff'
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px'
      },
      spacing: {
        'margin-desktop': '24px',
        'margin-mobile': '16px',
        'stack-lg': '32px',
        gutter: '24px',
        unit: '8px',
        'stack-sm': '8px',
        'stack-md': '16px'
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'title-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif']
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'title-lg': ['22px', { lineHeight: '28px', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'display-lg': ['57px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '16px', fontWeight: '500' }]
      }
    }
  },
  plugins: []
}
